version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - '3d:3a:c9:b6:32:24:12:46:3a:44:a5:ee:88:50:36:01'

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running tests
          command: npm test
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploy Master"
              npm run build
              npm run deploy:ci
            else
              echo "Not master branch so not deploying"
            fi
